# Generated by Django 4.2.30 on 2026-07-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
