# Generated by Django 4.2.30 on 2026-07-09 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Label',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('privacy', models.CharField(choices=[('A', 'Private'), ('B', 'Public')], default='A', max_length=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('assessment_status', models.CharField(choices=[('A', 'On-Track'), ('B', 'Delayed')], default='A', max_length=1)),
                ('extended_status', models.CharField(blank=True, choices=[('A', 'Archived')], max_length=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, db_column='fkAssignee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Project',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='fkproject', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.project')),
            ],
            options={
                'db_table': 'ProjectComment',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=1)),
                ('order', models.IntegerField(default=10)),
                ('color', models.CharField(default='#828383', max_length=7)),
            ],
            options={
                'db_table': 'ProjectStatus',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Task Title')),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, null=True)),
                ('enddatetime', models.DateTimeField(blank=True, null=True)),
                ('is_allday', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_type', models.CharField(blank=True, choices=[('E', 'Every Week Day'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1, null=True)),
                ('recurring_start_date', models.DateField(blank=True, null=True)),
                ('recurring_end_date', models.DateField(blank=True, null=True)),
                ('recurring_every', models.IntegerField(blank=True, null=True)),
                ('recurring_day', models.CharField(blank=True, max_length=13, null=True)),
                ('recurring_monthly_type', models.CharField(blank=True, choices=[('D', 'Day'), ('W', 'Week')], max_length=1, null=True)),
                ('recurring_monthly_date', models.IntegerField(blank=True, null=True)),
                ('recurring_monthly_week', models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Last')], null=True)),
                ('recurring_monthly_weekday', models.IntegerField(blank=True, null=True)),
                ('recurring_yearly_type', models.CharField(blank=True, choices=[('D', 'Day'), ('W', 'Week')], max_length=1, null=True)),
                ('recurring_yearly_month', models.IntegerField(blank=True, null=True)),
                ('recurring_yearly_date', models.IntegerField(blank=True, null=True)),
                ('recurring_yearly_week', models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Last')], null=True)),
                ('recurring_yearly_weekday', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('O', 'Open'), ('P', 'In Progress'), ('H', 'On Hold'), ('C', 'Complete')], default='O', max_length=1)),
                ('extended_status', models.CharField(blank=True, choices=[('A', 'Archived')], max_length=1, null=True)),
                ('task_type', models.CharField(blank=True, choices=[('N', 'Activity'), ('A', 'Appointment'), ('M', 'Meeting'), ('E', 'Event'), ('C', 'Call'), ('B', 'Client Meeting'), ('D', 'BD Call'), ('F', 'Client Interview'), ('J', 'Face 2 Face')], max_length=1, null=True)),
                ('timezone', models.CharField(blank=True, max_length=30, null=True)),
                ('completed_percentage', models.IntegerField(default=0)),
                ('include_weekend', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('assessment_status', models.CharField(choices=[('A', 'On-Track'), ('B', 'Delayed')], default='A', max_length=1)),
                ('is_sla', models.BooleanField(default=False)),
                ('is_reminder', models.BooleanField(default=False)),
                ('reminder_type', models.CharField(blank=True, choices=[('M', 'Minutes'), ('H', 'Hours'), ('D', 'Daily')], max_length=1, null=True)),
                ('reminder_before', models.IntegerField(blank=True, default=0, null=True)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('is_reminderall', models.BooleanField(blank=True, null=True)),
                ('external_ref', models.CharField(blank=True, max_length=250, null=True)),
                ('ticket_id', models.CharField(blank=True, max_length=25, null=True)),
                ('repeat_id', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, db_column='fkTaskowner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='fkCreated_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Task',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_auto_remove', models.BooleanField(default=False)),
                ('remove_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(db_column='fkTask', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tasks.task')),
            ],
            options={
                'db_table': 'TaskNote',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reminder_type', models.CharField(choices=[('M', 'Minutes'), ('H', 'Hours'), ('D', 'Days')], default='H', max_length=1)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('remind_assignee', models.BooleanField(default=True)),
                ('remind_creator', models.BooleanField(default=True)),
                ('remind_members', models.BooleanField(default=True)),
                ('remind_custom_users', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, db_column='fkParent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_reminders', to='tasks.taskreminder')),
                ('task', models.ForeignKey(db_column='fkTask', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task')),
            ],
            options={
                'db_table': 'TaskReminder',
            },
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('module', models.CharField(default='tasks', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WorkGroup',
                'unique_together': {('name', 'created_by', 'module')},
            },
        ),
        migrations.CreateModel(
            name='WorksheetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('logged_on', models.DateTimeField(auto_now_add=True)),
                ('hours_spent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('task', models.ForeignKey(db_column='fkTask', on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='tasks.task')),
                ('user', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.DO_NOTHING, related_name='worksheet_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worksheetLog',
                'ordering': ['-logged_on'],
            },
        ),
        migrations.CreateModel(
            name='WorkGroupHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(db_column='fkChild', on_delete=django.db.models.deletion.CASCADE, related_name='parent_groups', to='tasks.workgroup')),
                ('parent', models.ForeignKey(blank=True, db_column='fkParent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='tasks.workgroup')),
            ],
            options={
                'db_table': 'WorkGroupHierarchy',
            },
        ),
        migrations.CreateModel(
            name='TaskStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, choices=[('O', 'Open'), ('P', 'In Progress'), ('H', 'On Hold'), ('C', 'Complete')], default='O', max_length=1, null=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(db_column='fkTask', on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='tasks.task')),
            ],
            options={
                'db_table': 'TaskStatusUpdate',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='TaskReminderMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.ForeignKey(db_column='fkTaskReminder', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.taskreminder')),
                ('user', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TaskReminderMember',
            },
        ),
        migrations.CreateModel(
            name='TaskRejectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='fkCreated_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(db_column='fkTask', on_delete=django.db.models.deletion.CASCADE, related_name='reject_comments', to='tasks.task')),
            ],
            options={
                'db_table': 'TaskRejectComment',
            },
        ),
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=1)),
                ('color', models.CharField(default='#fad6b7', max_length=7)),
                ('order', models.IntegerField(default=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_priorities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TaskPriority',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('startdatetime', models.DateTimeField()),
                ('enddatetime', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('U', 'Yet to Schedule')], default='U', max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(db_column='fkTask', on_delete=django.db.models.deletion.CASCADE, related_name='planners', to='tasks.task')),
            ],
            options={
                'db_table': 'TaskPlanner',
                'ordering': ['startdatetime'],
            },
        ),
        migrations.CreateModel(
            name='TaskNoteHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(db_column='fkChild', on_delete=django.db.models.deletion.CASCADE, related_name='note_child', to='tasks.tasknote')),
                ('parent', models.ForeignKey(db_column='fkParent', on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_parent', to='tasks.tasknote')),
            ],
            options={
                'db_table': 'TaskNoteHeirarchy',
            },
        ),
        migrations.CreateModel(
            name='TaskNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tasks.models.task_note_attachment_upload_to)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(db_column='fkTaskNote', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.tasknote')),
            ],
            options={
                'db_table': 'TaskNoteAttachment',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#828383', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(db_column='fkProject', on_delete=django.db.models.deletion.CASCADE, related_name='task_lists', to='tasks.project')),
            ],
            options={
                'db_table': 'TaskList',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(db_column='fkTask', on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='tasks.task')),
            ],
            options={
                'db_table': 'TaskCheckList',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=tasks.models.task_attachment_upload_to)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(db_column='fkTask', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TaskAttachment',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(blank=True, db_column='fkTaskPriority', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.taskpriority'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, db_column='fkproject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='reportee',
            field=models.ForeignKey(blank=True, db_column='fkReportee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_to_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(blank=True, db_column='fktasklist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.tasklist'),
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(db_column='fkproject', on_delete=django.db.models.deletion.CASCADE, related_name='parent_project', to='tasks.project')),
                ('parent', models.ForeignKey(db_column='fksubproject', on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='tasks.project')),
            ],
            options={
                'db_table': 'Subproject',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='fkProject', on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='tasks.project')),
                ('status', models.ForeignKey(blank=True, db_column='fkStatus', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.projectstatus')),
            ],
            options={
                'db_table': 'ProjectStatusUpdate',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCommentHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(db_column='fkChild', on_delete=django.db.models.deletion.CASCADE, related_name='comment_child', to='tasks.projectcomment')),
                ('parent', models.ForeignKey(db_column='fkParent', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_parent', to='tasks.projectcomment')),
            ],
            options={
                'db_table': 'ProjectCommentHeirarchy',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, db_column='fkStatus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.projectstatus'),
        ),
        migrations.CreateModel(
            name='WorkGroupProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(db_column='fkProject', on_delete=django.db.models.deletion.CASCADE, to='tasks.project')),
                ('work_group', models.ForeignKey(db_column='fkWorkgroup', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tasks.workgroup')),
            ],
            options={
                'db_table': 'WorkGroupProject',
                'unique_together': {('work_group', 'project')},
            },
        ),
        migrations.CreateModel(
            name='TrackTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_on', models.CharField(choices=[('N', 'Disabled'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='N', max_length=1)),
                ('task', models.ForeignKey(db_column='fkTask', on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='tasks.task')),
                ('user', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.CASCADE, related_name='tracked_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TrackTask',
                'unique_together': {('user', 'task')},
            },
        ),
        migrations.CreateModel(
            name='TrackProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_on', models.CharField(choices=[('N', 'Disabled'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='N', max_length=1)),
                ('project', models.ForeignKey(db_column='fkProject', on_delete=django.db.models.deletion.CASCADE, to='tasks.project')),
                ('user', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TrackProject',
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='TaskMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Can Edit'), ('V', 'Can View'), ('C', 'Can Comment'), ('D', 'Can Delete')], max_length=1)),
                ('task', models.ForeignKey(db_column='fktask', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.task')),
                ('user', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TaskMember',
                'unique_together': {('task', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(db_column='fkLabel', on_delete=django.db.models.deletion.CASCADE, to='tasks.label')),
                ('task', models.ForeignKey(db_column='fkTask', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='tasks.task')),
            ],
            options={
                'db_table': 'TaskLabel',
                'unique_together': {('label', 'task')},
            },
        ),
        migrations.CreateModel(
            name='TaskHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(db_column='fkTaskchild', on_delete=django.db.models.deletion.CASCADE, related_name='subtask_children', to='tasks.task')),
                ('parent', models.ForeignKey(blank=True, db_column='fkTaskparent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtask_parents', to='tasks.task')),
            ],
            options={
                'db_table': 'TaskHierarchy',
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Can Edit'), ('V', 'Can View'), ('C', 'Can Comment'), ('D', 'Can Delete')], max_length=1)),
                ('membership', models.CharField(choices=[('P', 'Project'), ('T', 'Task')], default='P', max_length=1)),
                ('project', models.ForeignKey(db_column='fkProject', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.project')),
                ('user', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProjectMember',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BookmarkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(db_column='fkProject', on_delete=django.db.models.deletion.CASCADE, to='tasks.project')),
                ('user', models.ForeignKey(db_column='fkRoleuser', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BookmarkProject',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
